import{a as y,S as h,i as L}from"./assets/vendor-2618a76b.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function n(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerpolicy&&(s.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?s.credentials="include":r.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(r){if(r.ep)return;r.ep=!0;const s=n(r);fetch(r.href,s)}})();const q=document.querySelector(".search-form"),b=document.querySelector(".loader"),M=document.querySelector(".gallery"),v="41928121-1cda58f07b164a8f6335ccf06",S=document.querySelector(".search-btn"),B=document.querySelector(".load-btn"),e={form:q,API_KEY:v,searchBtn:S,gallery:M,loader:b,loadMoreBtn:B};e.loader.style.display="none";y.defaults.baseURL="https://pixabay.com/api";const l="is-hidden",o={query:"",page:1,maxPage:0,pageSize:15},P=new h(".gallery-item a",{captionsData:"alt",captionDelay:250});e.form.addEventListener("submit",k);async function k(t){if(t.preventDefault(),e.gallery.innerHTML="",e.loadMoreBtn.classList.add(l),o.query=e.form.query.value.trim(),!o.query){d("The search field can't be empty! Please, enter your request!");return}try{const{hits:a,total:n}=await f(o.query);o.maxPage=Math.ceil(n/15),m(a,e.gallery),a.length>0?(e.loadMoreBtn.classList.remove(l),e.loadMoreBtn.addEventListener("click",w)):(e.loadMoreBtn.classList.add(l),d("Sorry, there are no images matching your search query. Please, try again!")),u(!1)}catch(a){console.log(a)}finally{e.form.reset(),o.page===o.maxPage&&(e.loadMoreBtn.classList.add(l),d("We're sorry, but you've reached the end of search results!"))}}async function w(){o.page+=1;try{u(!0),e.loadMoreBtn.classList.add(l);const{hits:t}=await f(o.query,o.page);m(t,e.gallery),u(!1),x(),e.loadMoreBtn.classList.remove(l)}catch(t){console.log(t)}finally{o.page===o.maxPage&&(e.loadMoreBtn.classList.add(l),d("We're sorry, but you've reached the end of search results!"))}}async function f(t,a=1){return u(!0),y.get("/",{params:{key:e.API_KEY,q:o.query,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:a}}).then(({data:n})=>n)}function m(t){const a=t.map(({webformatURL:n,largeImageURL:i,tags:r,likes:s,views:c,comments:g,downloads:p})=>`
        <li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${n}"
      alt="${r}"
    />
    <p class="gallery-descr">likes: <span class="descr-span">${s}</span> views: <span class="descr-span">${c}</span> comments: <span class="descr-span">${g}</span> downloads: <span class="descr-span">${p}</span></p>
  </a>
</li>`).join("");e.gallery.insertAdjacentHTML("beforeend",a),P.refresh()}function d(t){L.show({class:"error-svg",position:"topRight",icon:"error-svg",message:t,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function u(t=!0){e.loader.style.display=t?"inline-block":"none"}function x(){const t=document.querySelector(".gallery-link").getBoundingClientRect();window.scrollBy({top:t.height*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
