import{a as f,S as h,i as L}from"./assets/vendor-2618a76b.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function l(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerpolicy&&(t.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?t.credentials="include":r.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(r){if(r.ep)return;r.ep=!0;const t=l(r);fetch(r.href,t)}})();const b=document.querySelector(".search-form"),q=document.querySelector(".loader"),M=document.querySelector(".gallery"),v="41928121-1cda58f07b164a8f6335ccf06",S=document.querySelector(".search-btn"),B=document.querySelector(".load-btn"),e={form:b,API_KEY:v,searchBtn:S,gallery:M,loader:q,loadMoreBtn:B};e.loader.style.display="none";f.defaults.baseURL="https://pixabay.com/api";const n="is-hidden",s={query:"",page:1,maxPage:0,pageSize:15},P=new h(".gallery-item a",{captionsData:"alt",captionDelay:250});e.form.addEventListener("submit",k);async function k(a){if(a.preventDefault(),s.page=1,e.gallery.innerHTML="",e.loadMoreBtn.classList.add(n),s.query=e.form.query.value.trim(),!s.query){d("The search field can't be empty! Please, enter your request!");return}try{const{hits:o,total:l}=await y(s);s.maxPage=Math.ceil(l/s.page),g(o,e.gallery),o.length>0?(e.loadMoreBtn.classList.remove(n),e.loadMoreBtn.addEventListener("click",w)):(e.loadMoreBtn.classList.add(n),d("Sorry, there are no images matching your search query. Please, try again!")),u(!1)}catch(o){console.log(o)}finally{e.form.reset(),s.page===s.maxPage&&(e.loadMoreBtn.classList.add(n),d("We're sorry, but you've reached the end of search results!"))}}async function w(){s.page+=1;try{u(!0),e.loadMoreBtn.classList.add(n);const{hits:a}=await y(s.query,s.page);g(a,e.gallery),u(!1),x(),e.loadMoreBtn.classList.remove(n)}catch(a){console.log(a)}finally{s.page===s.maxPage&&(e.loadMoreBtn.classList.add(n),d("We're sorry, but you've reached the end of search results!"))}}async function y(a=1){return u(!0),f.get("/",{params:{key:e.API_KEY,q:s.query,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:a}})}function g(a){const o=a.map(({webformatURL:l,largeImageURL:i,tags:r,likes:t,views:c,comments:p,downloads:m})=>`
        <li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${l}"
      alt="${r}"
    />
    <p class="gallery-descr">likes: <span class="descr-span">${t}</span> views: <span class="descr-span">${c}</span> comments: <span class="descr-span">${p}</span> downloads: <span class="descr-span">${m}</span></p>
  </a>
</li>`).join("");e.gallery.insertAdjacentHTML("beforeend",o),P.refresh()}function d(a){L.show({class:"error-svg",position:"topRight",icon:"error-svg",message:a,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function u(a=!0){e.loader.style.display=a?"inline-block":"none"}function x(){const a=document.querySelector(".gallery-link").getBoundingClientRect();window.scrollBy({top:a.height*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
